source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.3'
pod 'SwiftyJSON', '~> 2.2.1'
pod 'Kingfisher', '~> 1.4'
pod 'pop', '~> 1.0'
pod 'ReactiveCocoa'
